pluggy.py, testing/test_pluggy.py
Related to pytest-dev/pytest#932
=> Add has_plugin method to PluginManager

CHANGELOG, pluggy.py, testing/test_pluggy.py
@vodik this contains some further fixes and a docstring for call_historic.
=> fix historic hook calling some more, add docstring

CHANGELOG, pluggy.py, testing/test_pluggy.py
this does limit use of arbitrary callable objects
however i feel that is a welcome limitation
=> fix #17 by considering only routines

CHANGELOG.rst, pluggy/__init__.py
=> Update changelog and version for next patch release

CHANGELOG.rst
Added changelog entries for the notable [PR list since `0.5.2`](https://github.com/pytest-dev/pluggy/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%3A%3E2017-09-06%20).
Let me know if anything looks out of place.
=> 0.6.0 Minor release

docs/index.rst
I only spotted this after filing the other PR, sorry for the noise :)
=> one more typo

docs/index.rst
=> Add missing 'self' parameter to hookimpl in docs

HOWTORELEASE.rst, changelog/README.rst, changelog/_template.rst, pyproject.toml, scripts/release.py, tox.ini
Mostly borrowed by pytest and tox. 😉 
Fix #66
=> Use towncrier and a custom tox environment to prepare a release

changelog/110.bugfix.rst, changelog/116.removal.rst, changelog/117.trivial.rst, changelog/122.feature.rst, changelog/123.doc.rst, changelog/131.feature.rst, changelog/136.doc.rst, changelog/138.feature.rst, changelog/153.trivial.rst, changelog/156.trivial.rst, changelog/66.feature.rst
=> Add newsfragments for 0.7.0 release!

pyproject.toml
(btw sorry to push branches directly to the repo, I'm in a hurry so I'm doing this using the GH UI).
=> Use "pluggy" in changelog title

docs/index.rst
=> Update number of pytest plugins in the docs

.travis.yml, changelog/187.bugfix.rst, pluggy/hooks.py, tox.ini
=> Add testing for pypy3

docs/index.rst
* setup.py was missing from the Index.rst file but was necessary for the following `pip install` command
* fixed typo in `add_hookspecs`
=> Minor documentation improvements

CHANGELOG.rst
No sure how this got messed up...
=> Fix CHANGELOG for 0.10.0

src/pluggy/_result.py, src/pluggy/hooks.py, src/pluggy/manager.py, testing/test_details.py
These are some trivial cleanups. See the commit messages for some explanations.
=> Small cleanups

docs/index.rst
=> docs: fix broken intersphinx references

.github/workflows/main.yml, .travis.yml, tox.ini
pytest changed the branch name.
=> tox,ci: change pytestmaster -> pytestmain

.github/workflows/main.yml, changelog/308.removal.rst, changelog/309.feature.rst, pyproject.toml, setup.cfg, setup.py, tox.ini
Some project changes in preparation for a 1.0 release.
=> Remove support for Python 3.5, add Python 3.9, move metadata from setup.py to setup.cfg, mark as Mature

docs/conf.py, src/pluggy/_tracing.py, src/pluggy/callers.py, src/pluggy/hooks.py, src/pluggy/manager.py, testing/test_details.py
=> Run pyupgrade --py36

.github/workflows/main.yml
pytest main has dropped Python 3.6.
=> Use py37 to test pytest main branch

src/pluggy/_hooks.py, src/pluggy/_manager.py, src/pluggy/_result.py, testing/test_details.py
Please see the commits! I'm looking into improving `subset_hook_caller`, and these are some semi-related changes that would help with that.
=> Misc small improvements

src/pluggy/_hooks.py, testing/test_invocations.py
=> Remove manual kwargs-only check in call

src/pluggy/_callers.py
We can avoid the `_Result` business entirely in this case.
I tend to think it's worth it, but it does add some duplication to the function.
Benchmark comparing after ("NOW") to main ("0001_main"):
```
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.3.2, pluggy-1.0.1.dev102+g470a002
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/ran/src/pluggy
configfile: tox.ini
plugins: benchmark-4.0.0
collected 15 items
testing/benchmark.py ...............                                     [100%]
------------------------------------------------------------------------------------------- …
```
=> callers: add fastpath for when all teardowns are new-style

.github/workflows/main.yml
- Add py312
- Stop using setup.py
=> ci: some updates

CHANGELOG.rst
=> Add note about 1.1.0 being yanked

CHANGELOG.rst, changelog/405.feature.rst
I've ran the downstream tests and they seem good AFAICT. So I think now it will go smoothly :)
=> Preparing release 1.2.0

.pre-commit-config.yaml, docs/conf.py, docs/examples/eggsample-spam/setup.py, docs/examples/eggsample/eggsample/__init__.py, docs/examples/eggsample/eggsample/hookspecs.py, docs/examples/eggsample/eggsample/host.py, docs/examples/eggsample/setup.py, docs/examples/toy-example.py, pyproject.toml, scripts/release.py, scripts/towncrier-draft-to-file.py, src/pluggy/__init__.py, src/pluggy/_callers.py, src/pluggy/_hooks.py, src/pluggy/_manager.py, testing/test_details.py, testing/test_hookcaller.py
See https://github.com/pytest-dev/pytest/pull/11885#issuecomment-1915702181. and https://github.com/pytest-dev/pluggy/pull/476#issuecomment-1953152356
=> Migrate from ``reorder-python-imports`` / ``black`` to ``ruff`` / ``isort``

.github/workflows/main.yml
New feature in the PyPI publish action.
=> Publish package with attestations
