pytest-dev/pluggy

- pluggy.py
- test_pluggy.py
inspect.getargspec is deprecated on Python 3.5
This is the corollary to pytest-dev/pytest#1009
> Use inspect.signature instead of inspect.getargspec

- pluggy.py
This is an attempt at addressing https://github.com/hpk42/pluggy/issues/7.
It might get handled better, e.g. in pytest itself, but this makes it at least be more verbose and mentions the source of the error (the plugin causing it).
Traceback (most recent call last):
File "…/pluggy/pluggy.py", line 502, in load_setuptools_entrypoints
plugin = ep.load()
File "…/pyenv/project/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2354, in load
self.require(*args, **kwargs)
File "…/pyenv/project/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2371, in require
items = working_set.resolve(reqs, env, installer)
File "…/pyenv/project/lib/python3.4/site-packages/pkg_resources/__init__.py", line 844, in resolve
raise VersionConflict(dist, req).with_context(dependent_req) …
> Handle VersionConflict in `load_setuptools_entrypoints`

- pluggy.py
- testing/test_pluggy.py
- tox.ini
Fix #11 
Unfortunately this is not enough to solve the issue in Pytest, after this change I still get an error:
```
File "X:\pluggy\.env34\lib\site-packages\_pytest\config.py", line 206, in register
ret = super(PytestPluginManager, self).register(plugin, name)
File "X:\pluggy\.env34\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 360, in register
hookimpl_opts = self.parse_hookimpl_opts(plugin, name)
File "X:\pluggy\.env34\lib\site-packages\_pytest\config.py", line 181, in parse_hookimpl_opts
opts.setdefault(name, hasattr(method, name))
File "X:\pluggy\t\conftest.py", line 3, in __getattr__
raise Exception('cant touch me')
Exception: cant touch me
```
> Make pluggy more resilient when registering plugins with bad attributes

- pluggy.py
- testing/test_pluggy.py
Historic callbacks always immediately invoke all registered hooks, but the callback is **only** triggered on hooks that come from newly registered plugins. This change captures all information.
The added test fails on the current pluggy, so should catch any regressions should this be accepted.
I found this toying with pytest. The only historic hook in pytest is `pytest_namespace`, and the only reason this issue isn't a problem in pytest is the order in which things are setup. However if someone wanted to implement something similar inside a 3rd party plugin, this inconsistency means some results may be lost even though all hooks get triggered.
> Improve historic hook callbacks

- pluggy.py
- testing/test_pluggy.py
As per #19 this provides an update to `pluggy.varnames()`.
I've successfully run the unit tests across all interpreters on arch linux.
I'd like to test this across all dependent projects (`pytest`, `tox`, etc.) as well (and eventually get those tests integrated in a travis job for this project).
Note we'll need to move to `inspect.signature()` for py3.6...
> Modernize varnames function

- docs/examples/firstexample.py
- pluggy.py
- testing/conftest.py
- testing/test_details.py
- testing/test_helpers.py
- testing/test_hookrelay.py
- testing/test_method_ordering.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
Adding to all classes inheritance from `object` class.
All test green, excepts for Interpreters:
- python2.6
- python3.4
- pypy
as I don't have them. 
Hope it isn't an issue :)
> Moving to new style classes (object inheritance) - Issue #44

- pluggy.py
- testing/test_details.py
- testing/test_helpers.py
This add's proper warnings for hook calls which do not match the corresponding `hookspec`'s signature. The idea is to encourage callers of hooks to always keep up to date with the most recent spec.
This comes from discussion in #15.
@hpk42 @nicoddemus @RonnyPfannschmidt this is the first part of #34 which I have separated out to simplify the review and narrow focus.
> Hook call mismatch warnings

- .travis.yml
- testing/benchmark.py
- tox.ini
This adds some basic speed tests for the `_MultiCall` loop.
The goal is to extend this out so what we avoid performance degradation in addressing #23 and #15.
The next set of tests will include full code path(s) initiated by `_HookCaller` methods.
I was also thinking of adding collection speed tests.
Treat this PR as a first draft to get some opinions going.
So far the results are about what I'd expect - `pypy` killing it, `py27` and `py36` the runners up.
> Baseline benchmarking tests

- README.rst
- tox.ini
Some simple fix ups as per #47.
Resolves #47
> README improvements

- pluggy/__init__.py
- testing/test_hookrelay.py
Raise an explicit TypeError to alert the user that they are calling
a hookimpl incorrectly with positional args; keyword args are allowed
only.
Fixes #53
> Raise explicit error when impl called with pos args

- testing/test_hookrelay.py
- testing/test_method_ordering.py
Remove `test_method_ordering.test_decorator_functional` as it is
duplicate of an already incomplete test. 
Fix up `test_firstresult_definition` to be more more complete and actually test
that when multiple hooks are registered for a spec marked with `firstresult`
the first result is only ever returned.
Fixes #61
> Remove duplicate 'firstresult' test

- CHANGELOG.rst
I've updated the change log in prep for a `0.5.0` minor release. 
Let me know if you guys think anything else should be included / added.
Thanks!
> Fall 2017 release!

- pluggy/callers.py
- testing/test_hookrelay.py
Addresses #68...
If you guys are happy with this I'll push up a patch release `0.5.1`...
> Handle first result with None results

- CHANGELOG.rst
- pluggy/__init__.py
Fixes #68 and get's #69 into the wild stat!
> 0.5.1 patch release

- pluggy/__init__.py
This helps to differentiate from an official release and dev version.
Until #73 is done we have to remember to do that manually after the release as well.
> Update version to 0.5.2.dev

- pluggy/callers.py
- testing/test_hookrelay.py
I think this best solves pytest-dev/pytest#2730 and #71 and is pretty clear.
I'm of course open to a better way if you guys think of one.
Sorry about the delay...
> Firstresult madness

- pluggy/__init__.py
- testing/test_pluginmanager.py
> Fix error while issuing DeprecationWarning for __multicall__ usage

- pluggy/callers.py
This regression was discovered by pytest-dev/pytest#2744. 😅
> Add some __tracebackhide__ statements expected by pytest

- .travis.yml
- appveyor.yml
- tox.ini
Fix #76 
The environment for `pytest-features` is failing because pytest currently pins pluggy to `>=4.0,<5`, so `tox` cannot create the environment.
I propose we change `pytest`'s `setup.py` to optionally take the pluggy specification from an environment variable `_PYTEST_SETUP_PLUGGY_SPEC` if defined instead of what's encoded in `setup.py`,  roughly:
```python
def main():
install_requires = ['py>=1.4.33', 'six>=1.10.0','setuptools', 'pluggy>=0.4.0,<0.5']
```
Into:
```python
def main():
pluggy_spec = os.environ.get('_PYTEST_SETUP_PLUGGY_SPEC', 'pluggy>=0.4.0,<0.5')
install_requires = ['py>=1.4.33', 'six>=1.10.0','setuptools', pluggy_spec]
```
We will probably need to do something like that anyway for pytest-dev/pytest#2737.
> Test with pytest from master/features

- pluggy/__init__.py
- testing/test_method_ordering.py
- testing/test_pluginmanager.py
- tox.ini
- Fix two correct warnings
- Used pytest.warns() around a valid warning being issued
Should remove the warning exception for #81 when we tackle that.
Fix #78
> Turned warnings into errors

- pluggy/callers.py
- testing/test_details.py
This should fix the `pluggymaster` environment in pytest.
Guys I was wondering if it wouldn't be better instead of `get_result()` to have `result` as a read-only property, with the same semantics as `get_result()`? 
`outcome.result` is more user-friendly than `outcome.get_result()`. It seems we are not using one of the key benefits of properties of being able to change an attribute access into a property at some later time without breaking users.
> Re-add _Result.result as an attr which triggers a deprecation warning

- pluggy/__init__.py
- pluggy/callers.py
- testing/benchmark.py
- testing/test_multicall.py
For some weird reason the benchmark tests are turning out to be slightly slower for the `_multicall` cases?
I'm not sure if I'm testing something differently or if invoking 2 methods is faster then a single function?
I'm going to investigate deeper.
> Multicall to func

- testing/test_hookrelay.py
- testing/test_method_ordering.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
- testing/test_tracer.py
Fix #95: Resolve E741 errors
The E741 (Ambiguous variable name) error has been enabled in flake8 3.5.0, which imports pycodestyle 2.1.0 [1]. Resolve the warnings.
[1] https://github.com/PyCQA/pycodestyle/issues/598
> Fix #95: Resolve E741 errors

- testing/test_pluginmanager.py
This proves that #91 is a problem in `pytest` and not `pluggy`.
Thanks to @RonnyPfannschmidt for the fix about a year ago ;)
> Prove that `PluginManger.register()` ignores non-routines

- pluggy/__init__.py
- pluggy/callers.py
- testing/test_method_ordering.py
- testing/test_multicall.py
This fixes #99 as well as removes any direct references to `_HookCaller` inside of the multi call loops.
This makes the call loops fully self contained without requiring any knowledge of overlying abstractions.
> Self contained call loops

- .travis.yml
- CHANGELOG.rst
- appveyor.yml
- pluggy/__init__.py
- setup.py
- tox.ini
Fixes https://github.com/pytest-dev/pluggy/issues/92.
> Drop support for EOL Python 2.6 & 3.3

- setup.py
> Prevent installation in unsupported Python versions

- pluggy/__init__.py
- tox.ini
This function is deprecated and raises the warning.
DeprecationWarning: inspect.getargspec() is deprecated, use
inspect.signature() instead
While this suggests we use 'inspect.signature()', there's no reason to
use this instead of the 'inspect.getfullargspec()', which has almost
identical semantics to 'inspect.getargspec()' but handles kwargs-only
functions. For what we want though, this is a drop-in replacement.
Note that because 'inspect.getfullargspec()' isn't provided in Python
2.7, we may see slightly different behavior between Python 2 and 3 (e.g.
for the kwargs-only case above).  There's nothing we can do about this
without vendoring the entire function.
> Fix #81: Stop using 'inspect.getargspec()'

- pluggy/__init__.py
I noticed this while browsing the code. I don't see any `excludefunc` argument in PluginManager's constructor. Maybe it used to be there and was later removed?
> remove reference to missing 'excludefunc' arg in PluginManager docstring

- docs/api_reference.rst
- docs/index.rst
Some reference fixes after moving `_Result` into the `callers` module.
Can't come in until #117 has landed.
> Fix docs references

- pluggy/hooks.py
- testing/test_pluginmanager.py
Test requested for #110 since @rmfitzpatrick seems to be MIA.
Added the fix from that PR here.
> Test historic hook with no callback

- docs/index.rst
> Mention that wrappers are still invoked when using `firstresult`

- pluggy/manager.py
- testing/test_pluginmanager.py
The goal of this is to be able to call `.check_pending()` catching the exception, then unregister the plugin and print a message, allowing the program to continue without that plugin. If there is already a way to do this, I haven't found it.
> Add .plugin member to PluginValidationError to access failing plugin

- docs/index.rst
- pluggy/hooks.py
- pluggy/manager.py
- testing/test_details.py
this will be used later on in pytest to deprecate hooks we dont really use/support anymore so we can remove them in future
this can also be used to do futurewarnings for experimental hooks
> support adding per implementation warnings for hookspecs

- README.rst
- docs/index.rst
Resolves #128 and switches our `pypi` links to warehouse.
Tossed in docs for #123 as well.
> Document self arg and exception handling

- docs/index.rst
- pluggy/hooks.py
- testing/test_pluginmanager.py
It's a bad name, use `result_callback` instead.
Resolves #120
> Deprecate `proc` kwarg to call_historic()

- pluggy/manager.py
- testing/test_details.py
- testing/test_method_ordering.py
- testing/test_pluginmanager.py
Pertains to starting work on #116.
I'll have a corresponding PR to `pytest` to ensure the warning is avoided - turned out it's a trivial change.
> Deprecate implprefix

- pluggy/hooks.py
- testing/test_details.py
This is helpful when debugging hooks being called.
Example:
> <HookImpl plugin_name='testmon', plugin_file='/path/to/plugin.py'>
Using `"<HookImpl plugin=%r>" % (self.plugin,)` instead would result in:
> <HookImpl plugin=<module 'testmon.tox_testmon' from '/path/to/plugin.py'>>
> Add HookImpl.__repr__

- changelog/57.trivial.rst
- pluggy/hooks.py
- pluggy/manager.py
- testing/benchmark.py
- testing/test_hookcaller.py
Allows for easier introspection of spec definitions including function
signatures and hook options. Originally introduced to address ~#47~ #15 and #43 which
requires keeping track of spec default arguments values.
> Encapsulate spec definitions with a class

- README.rst
The pluggy package is hosted on conda-forge, so it is nice to promote
them and it also updates faster when there's a new release
> Use conda-forge badge instead of anaconda

- changelog/166.trivial.rst
- pluggy/manager.py
- testing/test_pluginmanager.py
> Adjust stacklevel of implprefix warning

- docs/conf.py
The new version of alabaster requires explicitly setting which sidebars
should be displayed. Copy `tox` for now.
Fixes #171
Hopefully this does it.
> Add html local toc sidebar to docs

- pluggy/manager.py
Correct the method name `add_hookspec` to `add_hookspecs` in the docstring of the `PluginManager` class.
> Fix method name `add_hookspecs` in docstring

- .pre-commit-config.yaml
This also fixes a warning:
```
[WARNING] Unexpected keys present on local => rst: python_version
```
> pre-commit autoupdate + fix config

- appveyor.yml
- docs/conf.py
- pluggy/manager.py
- setup.py
- testing/test_pluginmanager.py
This attempts to switch the backing metadata looking from `pkg_resources` (slow) to `importlib-metadata` (fast)
I had to expose one derived property on top of the `importlib_metadata` `Distribution` class to make it look like the `pkg_resources` one -- but otherwise this should be drop-in.
At least for pytest this isn't enough to get the full performance boost since `pytest` imports `pkg_resources` itself -- but baby steps!  I'll be following up with the pytest branch in https://github.com/pytest-dev/pytest/pull/5063
> Switch to importlib-metadata

- changelog/205.bugfix.rst
- docs/conf.py
- pluggy/manager.py
- setup.py
- testing/test_pluginmanager.py
Reverts pytest-dev/pluggy#199
Fixes #205
> Revert "Switch to importlib-metadata"

- .travis.yml
- appveyor.yml
- changelog/209.trivial.rst
- setup.py
- src/pluggy/hooks.py
Avoids a possible deprecation warning with inspect.getfullargspec()
Fixes https://github.com/pytest-dev/pluggy/issues/209
> Convert hooks.varnames() to inspect.signature() on Python 3

- src/pluggy/hooks.py
- testing/test_helpers.py
Introduced in https://github.com/pytest-dev/pluggy/pull/210
Note: In "normal" Python, exec exports the defined names, however in pytest, I needed to use globals.
> Fix a regression with keyword only arguments

- changelog/209.trivial.rst
- setup.py
- src/pluggy/hooks.py
As discussed in https://github.com/pytest-dev/pluggy/pull/212
This reverts commits:
* bebd02418f67d7a0f01ab27b9cfe7d0d7650faa9
* 39c6247294029447045f97d91d5a1a2af9be92ce
* 2008a3d5d164f745fb0d9550d3576dce6bf6c59f
* 68e56e553d69228e25ffab54d2bcc234433c3069
* 62f28acac8d1249e5b907c16256594b5a6697474
* ec28f027180961cdf86b21c8433d3b2f4c41af13
Closes #212
> Revert varnames() refactor to use inspect.Signature

- changelog/215.feature.rst
- docs/conf.py
- setup.py
- src/pluggy/manager.py
- testing/test_pluginmanager.py
I've fixed the `.egg` problem upstream, so we can try this again!
Originally introduced in #199, reverted in #206 to fix #205.
I validated that the fix works by doing the following:
1. First I created an egg of pluggy by running this: `python setup.py bdist_egg`
2. Next I created a small project which uses `pytest-runner`:
```python
from setuptools import setup
setup(
name='wat',
setup_requires=["pytest-runner"],
tests_require=["pytest"],
)
```
```python
def test(): pass
```
3. Then I seeded my egg into the directory which setuptools installs into
```bash
mkdir .eggs
cp ../dist/*.egg .eggs/
```
4. then I ran `python setup.py pytest` -- I made sure it didn't download a new egg for pluggy, here's the output of that
```
$ python setup.py pytest
running pytest
Searching for pytest
Reading …
```
> importlib-metadata again

- .travis.yml
- appveyor.yml
- changelog/222.trivial.rst
- docs/conf.py
- setup.py
- src/pluggy/manager.py
- testing/test_pluginmanager.py
- tox.ini
Fixes https://github.com/pytest-dev/pluggy/issues/222
Got `pytest: error: unrecognized arguments: -ra` with tox on 3.8 :(
> Replace importlib_metadata with importlib.metadata on Python 3.8+

- docs/index.rst
- src/pluggy/hooks.py
- testing/test_multicall.py
Please see the commit messages.
> A few minor fixes

- src/pluggy/manager.py
- testing/test_pluginmanager.py
This has the version switch in a central place only once.
Ref: https://github.com/pytest-dev/pluggy/pull/223/files#r315505111
> test_pluginmanager: use pluggy.manager.metadata

- src/pluggy/_tracing.py
- src/pluggy/hooks.py
- src/pluggy/manager.py
- testing/test_tracer.py
A few minor changes relating to the tracing stuff. Please see the commits.
> Code-level simplifications to tracing

- CHANGELOG.rst
- docs/api_reference.rst
- docs/conf.py
- docs/index.rst
- src/pluggy/hooks.py
- src/pluggy/manager.py
Closing #186.
Running `linkcheck` now yields only one broken link to [tgoodlet](https://github.com/tgoodlet) user account, rest are fixed. Also replaced hardcoded links with `intersphinx` refs where possible. Extended apidoc to a minimal amount of private classes/methods, enough just to fix the existing refs.
The second commit adds some crossrefs between the docstrings and some minor formatting improvements. This one is more a suggestion and I wouldn't mind throwing it away - check whether it really adds a significant amount of readability.
> References overhaul

- README.rst
Hi,
I am trying `pluggy`, and after reading the `README.md` short example I thought I knew what would be the output, but had to run the code to confirm.
This PR adds Python comments to the code block with the results. But perhaps it could go somewhere else if others have any suggestions?
Thanks for pluggy
Bruno
> Add the output of the example code

- src/pluggy/hooks.py
- src/pluggy/manager.py
- testing/test_hookcaller.py
This PR adds a `specname` option to `@hookimpl`.  If `specname` is provided, it will be used instead of the function name when matching this hook implementation to a hook specification during registration (allowing a plugin to register a hook implementation that was not named the same thing as the corresponding `hookspec`). 
(Edited:) This is related to #218 (though likely different than that poster’s intentions)
Most of the interesting discussion is happening in #218 (@RonnyPfannschmidt voiced some opposition to the idea at one point), and you can see my use-case/rationale for wanting this feature in https://github.com/pytest-dev/pluggy/issues/218#issuecomment-578554932.  But I figured since it's a small change, I would submit this so you could see exactly what I was proposing to make …
> add specname option to hookimpl

- .travis.yml
- appveyor.yml
- tox.ini
pytest does not use the `features` branch anymore.
> ci/tox: remove pytestfeatures

- src/pluggy/_result.py
- src/pluggy/callers.py
Originally proposed (and accepted by moi) in #227.
Relates to:
- fits with discussion in #244 the solution in #257 and further ideas and discussion in #260
- allows for solving a import cycle in #104
> Move `_Result` and friends to new module

- changelog/265.removal.rst
- src/pluggy/_result.py
- testing/test_deprecations.py
Since master is now 1.0, we can remove deprecated stuff.
> Remove deprecated _Result.result

- .travis.yml
- appveyor.yml
- changelog/267.removal.rst
- setup.py
- tox.ini
> Remove official support for Python 3.4

- .github/workflows/main.yml
- .travis.yml
- src/pluggy/_result.py
Because we moved things around between submitting and merging the PRs, the unused import slipped into master, which causes the CI to fail, so fix that.
Also move the `linting`, `docs` and `benchmark` jobs to GHA because it's nicer and provides a visible "Check" status. What's left on travis require coverage which I can't set up no GHA myself, I think.
> Fix unused import in master, move some jobs from Travis to GHA

- docs/index.rst
assuming you choose to merge #251, this PR adds a section to your docs about hook implementation naming and the `specname` option.
> add docs for specname

- .pre-commit-config.yaml
- tox.ini
I'm not an expert, but I can't run it otherwise if I only have Python 3.8 installed.
> Allow running `tox -e linting` with any python3

- changelog/116.removal.rst
- src/pluggy/manager.py
- testing/test_deprecations.py
- testing/test_pluginmanager.py
This has been deprecated for a while, let's remove it in pluggy 1.0.
Refs #116. Fixes #145.
pytest no longer uses it.
tox doesn't use it.
devpi [mentions it](https://github.com/devpi/devpi/search?q=implprefix&unscoped_q=implprefix) with comment "support old plugins, but emit deprecation warnings", does so in a future-compatible manner however (doesn't pass the `implprefix` argument to `PluginManager`, which this PR removes, but sets `_implprefix` attribute instead, which this PR now ignores). devpi uses `pluggy>=0.6.0,<1.0` so it's fine anyway.
> Remove deprecated implprefix support

- tox.ini
Was missed in 30a2f7c691c32e7ceb29ce52063773c21d3a2a0e.
> Remove pytestfeatures tox env

- src/pluggy/callers.py
- src/pluggy/hooks.py
- src/pluggy/manager.py
- testing/benchmark.py
- testing/test_multicall.py
~~*Note: includes PR #279, please ignore the duplicate commits (will rebase once that one is settled).*~~
This PR start to optimize the hook calling path, mostly for the benefit of pytest.
For this pytest file which we use as a useful benchmark of pytest overhead,
```py
import pytest
@pytest.mark.parametrize("x", range(5000))
def test_foo(x): pass
```
Before: `10752102 function calls (10196645 primitive calls) in 9.270 seconds`
After: `10351436 function calls (9896147 primitive calls) in 8.918 seconds`
The main change stems from looking at the stack trace of a hook call. Before this PR it was this (pytest often has several of these nested):
```
File "/pytest/src/_pytest/python.py", line 1561, in runtest
self.ihook.pytest_pyfunc_call(pyfuncitem=self)
File …
```
> Optimize hook calling a bit

- src/pluggy/manager.py
Simple fix for this error: https://github.com/python/importlib_metadata/issues/293
(similar to https://github.com/pytest-dev/py/issues/218)
> fix: dictionary changed size during iteration iterating on importlib_metadata.distributions()

- changelog/282.feature.rst
- src/pluggy/manager.py
- testing/test_details.py
- testing/test_pluginmanager.py
Previously this error was only reported when calling the hook. Now it is reported during registration.
Suggested by @maxnikulin in https://github.com/pytest-dev/pluggy/pull/257#discussion_r447416628.
> Validate that a hookwrapper's function is a generator function during registration

- setup.py
- tox.ini
Despite adding it also to pyproject.toml, it doesn't work for `pip
install -e .` and probably other stuff like that, so it got version
`0.0.0`.
> Restore use_scm_version in setup.py

- docs/index.rst
- src/pluggy/_manager.py
> Use refs instead of direct urls to link to pytest docs, fix internal crossrefs

- CHANGELOG.rst
- docs/index.rst
Looks like #251 was forgotten in the changes for 1.0.0?
> Include #251 in the release notes for 1.0.0

- .coveragerc
- .gitignore
- .pre-commit-config.yaml
- docs/conf.py
- pyproject.toml
- src/pluggy/__init__.py
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- src/pluggy/_tracing.py
- testing/benchmark.py
- testing/conftest.py
- testing/test_details.py
- testing/test_helpers.py
- testing/test_hookcaller.py
- testing/test_invocations.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
- testing/test_tracer.py
This adds type annotations to all pluggy code. This is a respin of #225 but now using Python 3 syntax.
The type annotations are not published, it will require some work for it to make sense, cleaning up the interface and imports and such. But I think internal type annotations are still useful for understand the code (I always have to relearn how stuff relate to each other when looking at pluggy) and as a linter.
In the meantime @RonnyPfannschmidt created #326. I think this PR is a better starting point because it almost doesn't change the code itself besides adding the types. Ronny's changes can be added on top maybe.
> Add type annotations

- testing/test_invocations.py
See https://pluggy.readthedocs.io/en/latest/#enforcing-spec-validation -
there was no test for the no validation case.
> Test calling a hook with no hookspec

- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- testing/test_details.py
- testing/test_hookcaller.py
- testing/test_pluginmanager.py
This PR contains 3 changes, which are (mostly) conceptually independent but better understood together.
The second commit fixes #346 and #347. The idea is, instead of creating a full-fledged HookCaller, create one which just proxies to the real HookCaller + the plugin filtering. The implementation is a bit hacky but the best I could come up after trying several approaches.
I ran the pytest testsuite and everything passes (after https://github.com/pytest-dev/pytest/pull/9512).
pluggy's benchmark suite looks good (not much difference, maybe a slight improvement). I still need to check pytest though, as pluggy's benchmark doesn't cover `subset_hook_caller` at all.
Please see the commits for details.
> Improve subset hook caller & related changes

- docs/index.rst
I hope this isn't seen as petty or wasting your time (I love this project!). This is just a small fix to update the document with three corrections where the word `then` (indicating time) was sometimes used in place of the word `than` (comparison). I was reading through the docs again today and noticed these.
> Tiny grammar correction

- testing/test_invocations.py
Minor typo fix on `testing/test_invocations.py`.
> Fix typo on test_invocations.py

- .github/workflows/main.yml
- .pre-commit-config.yaml
- changelog/364.feature.rst
- changelog/364.removal.rst
- docs/conf.py
- setup.cfg
- tox.ini
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
And drop EOL Python 3.6.
Plus some other updates to fix the CI.
> Add support for Python 3.11 and drop EOL 3.6

- src/pluggy/_hooks.py
- testing/test_helpers.py
Switch to `inspect.signature` instead of `inspect.getfullargspec` to properly support wrapper chains (decorated functions) - see details in issue #358 .
In the proposed change I tried to do the minimal required changes to `varnames`.
> Proposed fix for issue #358

- .github/workflows/main.yml
- .pre-commit-config.yaml
- docs/examples/eggsample/eggsample/host.py
- docs/examples/eggsample/setup.py
- scripts/release.py
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- testing/benchmark.py
- testing/conftest.py
- testing/test_details.py
- testing/test_helpers.py
- testing/test_hookcaller.py
- testing/test_invocations.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
- testing/test_tracer.py
- tox.ini
Also:
- Change the order of the hooks, so those that change code but do not care about formatting run first, then black, and finally checkers like `mypy`.
- Drop `linting` environment: not needed anymore given we are using pre-commit.ci.
- Do not run `docs` on CI: we already use readthedocs.io for that (but keep tox environment for local execution).
> Add reorder-python-imports and autoflake hooks

- pyproject.toml
> pyproject.toml: remove `wheel` build-system requires

- testing/benchmark.py
In d22672d954866276e04c8a6e4d3a4ba822604314 I didn't notice that using `pedantic` means the benchmark will only run for 1 round unless you tell it otherwise.
> benchmark: fix benchmark running for only 1 round

- docs/index.rst
- src/pluggy/_callers.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- testing/test_invocations.py
- testing/test_multicall.py
The excinfo triplet is a legacy concept, these days the exception instance itself carries the necessary info.
Switch the internal implementation to store just the exception instead of the triplet, and add an `exception` property to access it without the excinfo annoyance.
> result: use exception instead excinfo triplet

- changelog/394.feature.rst
- docs/api_reference.rst
- docs/index.rst
- src/pluggy/_result.py
- testing/test_multicall.py
Hookwrappers do not currently provide a public, proper way to override or force an exception. Raising directly from the hookwrapper causes further wrappers to be skipped, but this is not something we want to change at this point, for fear of breaking things, and because we are adding a replacement. See #244 on this issue.
> result: add `result.force_exception` API

- pyproject.toml
Without it some legacy mode is used.
> pyproject.toml: add missing `build-backend` setting

- .coveragerc
- changelog/260.feature.rst
- docs/index.rst
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- testing/benchmark.py
- testing/test_details.py
- testing/test_hookcaller.py
- testing/test_invocations.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
This implements the idea from #260. I think it makes pluggy more elegant, and also provides a backward compatible fix for #244 (replaces #257).
> Hook wrapping without `_Result`

- src/pluggy/_callers.py
No reason to not do it also for exceptions. Was a thinko.
> callers: do `.close()` also in the `throw` case

- src/pluggy/_manager.py
Added in 0b45952cf9f8fece53a5efd1cf40466b5714c17f. Broke two downstream projects:
- devpi: https://github.com/devpi/devpi/issues/980
- A test in tox which mocks something in PluginManager.
It is not worth it.
> manager: remove `__slots__` from `PluginManager`

- src/pluggy/_hooks.py
They are specified in the base class, it's wrong to specify in the subclass.
> hooks: remove a couple of unnecessary slots from `_SubsetHookCaller`

- RELEASING.rst
- downstream/.gitignore
- downstream/README.md
- downstream/conda.sh
- downstream/datasette.sh
- downstream/devpi.sh
- downstream/hatch.sh
- downstream/pytest.sh
- downstream/tox.sh
> Add scripts for downstream testing

- .coveragerc
- CHANGELOG.rst
- changelog/405.feature.rst
- docs/index.rst
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- testing/benchmark.py
- testing/test_details.py
- testing/test_hookcaller.py
- testing/test_invocations.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
Previously new-style wrappers were implied by the function being a generator, however that broke a use case of a non-wrapper impl being a generator as a way to return an Iterator result. This is legitimate, and used at least by conda (see #403).
Therefore, change to require an explicit `wrapper=True`. Also adds a test for the iterator-returning case.
Fix #405.
> Make new-style wrappers use explicit `wrapper=True`

- src/pluggy/_hooks.py
- testing/test_hookcaller.py
Hi! I've spent some time trying to nail down hook registration error:
```python
INTERNALERROR>     pluginmanager.add_hookspecs(Hookspec)
INTERNALERROR>   File "contrib/python/pluggy/py3/pluggy/_manager.py", line 175, in add_hookspecs
INTERNALERROR>     hc.set_specification(module_or_class, spec_opts)
INTERNALERROR>   File "contrib/python/pluggy/py3/pluggy/_hooks.py", line 200, in set_specification
INTERNALERROR>     assert not self.has_spec()
INTERNALERROR> AssertionError
```
This PR raises `RuntimeError` with detailed message which should ease developer's life a bit:
```python
E           RuntimeError: Hook 'conflict' is already registered within namespace <class 'test_hookcaller.test_hook_conflict.<locals>.Api1'>
src/pluggy/_hooks.py:341: RuntimeError
```
> Detailed error message on hook registration conflict

- src/pluggy/_tracing.py
Reason: `pytest` uses `TagTracer.setwriter(None)` when unsetting the tracer in https://github.com/pytest-dev/pytest/blob/1de0923e83e3258709559d86d142adaab65a42d8/src/_pytest/helpconfig.py#L126. This PR adjusts the typing of `TagTracer.setwriter` to support this case.
> ensure the type hints support the writer unsetting in tagtracer

- .github/workflows/main.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- changelog/426.removal.rst
- docs/conf.py
- setup.cfg
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- testing/test_pluginmanager.py
- tox.ini
> Remove support for Python 3.7

- .readthedocs.yml
- CHANGELOG.rst
- docs/api_reference.rst
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- src/pluggy/__init__.py
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- testing/test_hookcaller.py
- testing/test_pluginmanager.py
- tox.ini
Handles some items from #428, but not finished yet.
> Some steps towards exporting our typings

- changelog/428.feature.rst
- docs/api_reference.rst
- setup.cfg
- src/pluggy/__init__.py
- src/pluggy/_tracing.py
This exports our typing, fixing #428.
I ran pytest mypy against this (see https://github.com/pytest-dev/pytest/pull/11353), which required a couple of fixes in pluggy - see first 2 commits. Other than that, should be good.
> Export pluggy's typing

- src/pluggy/_manager.py
Refs https://github.com/pytest-dev/pluggy/pull/445#issuecomment-1732573535
This package is needed for `load_setuptools_entrypoints`, but it is quite slow to import. While most users do use
`load_setuptools_entrypoints`, maybe some don't, so let's let them avoid the cost.
For `import pluggy`:
Before: 36ms
After:  11ms
> Defer loading of importtlib.metadata

- docs/index.rst
Noticed that part of the text is not being formatted correctly in readthedocs:
After this PR:
> Fix formatting in wrappers docs

- CHANGELOG.rst
> CHANGELOG: fix errors in 1.0.0 entry

- src/pluggy/_hooks.py
- testing/test_hookcaller.py
Fix `call_extra` extra methods getting ordered before everything else when there is at least one wrapper impl.
Fix #441.
Regressed in https://github.com/pytest-dev/pluggy/commit/63b7e908b4b22c30d86cd2cff240b3b7aa6da596 - pluggy 1.1.0.
This is adapted from #461 by @vishutupili, separate PR because the existing one can't be updated. Closes #461. Reviewed by me.
> Fix `call_extra` call ordering regression in pluggy 1.1.0

- src/pluggy/_hooks.py
- testing/test_pluginmanager.py
when the other plugins implement the same hook itself.
Fix #438.
Regressed in 63b7e908b4b22c30d86cd2cff240b3b7aa6da596 - pluggy 1.1.0.
Went with the simple solution described in the issue for now, basically undoing most of the rationale for 63b7e908b4b22c30d86cd2cf (though I think it's still better to have a single `_hookimpls` list).
> hooks: fix plugins registering other plugins in a hook

- changelog/463.feature.rst
- docs/api_reference.rst
- src/pluggy/__init__.py
- src/pluggy/_callers.py
- src/pluggy/_result.py
- src/pluggy/_warnings.py
- testing/test_warnings.py
> Warn when old-style hookwrapper raises during teardown

- src/pluggy/_manager.py
- testing/test_pluginmanager.py
Pytest currently accesses internals to do this:
https://github.com/pytest-dev/pytest/blob/1b78de4e21d55983422e7327a51304ef0fc61679/src/_pytest/config/__init__.py#L740-L746 Let's provide a proper API for this.
> Add `PluginManager.unblock` method to unblock a name

- docs/index.rst
It wasn't obvious to me why the new `specname` feature exists until I figured out it means I can register the same hook multiple times in a single file.
> Clarify purpose of specname

- docs/index.rst
The Kedro link on https://pluggy.readthedocs.io/en/stable/#more-real-world-examples
> To see how `pluggy` is used in the real world, have a look at these projects documentation and source code:
> 
> -   [pytest](https://docs.pytest.org/en/latest/how-to/writing_plugins.html#writing-plugins "(in pytest v8.1.0.dev95+g2a77f8d)")
> -   [tox](https://tox.wiki/en/latest/plugins.html "(in Python v4.12)")
> -   [devpi](https://devpi.net/docs/devpi/devpi/stable/+doc/devguide/index.html "(in devpi v6.9)")
> -   [kedro](https://docs.kedro.org/en/latest/kedro.framework.hooks.specs.html "(in kedro v0.19)")
Links to https://docs.kedro.org/en/latest/kedro.framework.hooks.specs.html which returns a 404 error
I think https://docs.kedro.org/en/latest/hooks/introduction.html is a better page to link to here.
> Fix broken Kedro hooks link

- .pre-commit-config.yaml
- docs/conf.py
- docs/examples/eggsample-spam/setup.py
- docs/examples/eggsample/eggsample/__init__.py
- docs/examples/eggsample/eggsample/hookspecs.py
- docs/examples/eggsample/eggsample/host.py
- docs/examples/eggsample/setup.py
- docs/examples/toy-example.py
- pyproject.toml
- scripts/release.py
- scripts/towncrier-draft-to-file.py
- src/pluggy/__init__.py
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- src/pluggy/_tracing.py
- testing/benchmark.py
- testing/test_details.py
- testing/test_hookcaller.py
- testing/test_pluginmanager.py
> Upgrade tools, apply black 2024's style inside blackendoc

- .github/FUNDING.yml
- README.rst
- SECURITY.md
- TIDELIFT.rst
This updates the docs now that `pluggy` is also on Tidelift.
> Lift pluggy

- pyproject.toml
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
* switch ruff config to extend-select and enable UP rules
* make mypy --strict pass for src
> minor ruff and mypy cleanups

- .github/workflows/main.yml
- pyproject.toml
- tox.ini
Python 3.13 is due out today! 🚀 
https://peps.python.org/pep-0719/
> Add support for Python 3.12 and 3.13

- changelog/544.bugfix.rst
- src/pluggy/_callers.py
- testing/test_multicall.py
Raising a StopIteration in a generator triggers a RuntimeError.
If the RuntimeError of a generator has the passed in StopIteration as cause
resume with that StopIteration as normal exception instead of failing with the RuntimeError.
closes #544
> fix #544: Correctly pass StopIteration trough wrappers

- .github/workflows/main.yml
- .pre-commit-config.yaml
- changelog/556.removal.rst
- pyproject.toml
- src/pluggy/_callers.py
- src/pluggy/_hooks.py
- src/pluggy/_manager.py
- src/pluggy/_result.py
- src/pluggy/_tracing.py
- testing/test_hookcaller.py
- testing/test_invocations.py
- testing/test_multicall.py
- testing/test_pluginmanager.py
- testing/test_tracer.py
- tox.ini
Also run pre-commit (with pyupgrade) on all files.
> Drop Python 3.8 support
